#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : s3fs-fuse
Version  : 1.91
Release  : 9
URL      : https://github.com/s3fs-fuse/s3fs-fuse/archive/v1.91/s3fs-fuse-1.91.tar.gz
Source0  : https://github.com/s3fs-fuse/s3fs-fuse/archive/v1.91/s3fs-fuse-1.91.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-2.0
Requires: s3fs-fuse-bin = %{version}-%{release}
Requires: s3fs-fuse-license = %{version}-%{release}
Requires: s3fs-fuse-man = %{version}-%{release}
BuildRequires : attr-dev
BuildRequires : openssl-dev
BuildRequires : pkgconfig(fuse)
BuildRequires : pkgconfig(gnutls)
BuildRequires : pkgconfig(libcrypto)
BuildRequires : pkgconfig(libcurl)
BuildRequires : pkgconfig(libxml-2.0)
BuildRequires : pkgconfig(nettle)
BuildRequires : pkgconfig(nss)

%description
# s3fs
s3fs allows Linux, macOS, and FreeBSD to mount an S3 bucket via FUSE.
s3fs preserves the native object format for files, allowing use of other
tools like [AWS CLI](https://github.com/aws/aws-cli).
[![s3fs-fuse CI](https://github.com/s3fs-fuse/s3fs-fuse/workflows/s3fs-fuse%20CI/badge.svg)](https://github.com/s3fs-fuse/s3fs-fuse/actions)
[![Twitter Follow](https://img.shields.io/twitter/follow/s3fsfuse.svg?style=social&label=Follow)](https://twitter.com/s3fsfuse)

%package bin
Summary: bin components for the s3fs-fuse package.
Group: Binaries
Requires: s3fs-fuse-license = %{version}-%{release}

%description bin
bin components for the s3fs-fuse package.


%package license
Summary: license components for the s3fs-fuse package.
Group: Default

%description license
license components for the s3fs-fuse package.


%package man
Summary: man components for the s3fs-fuse package.
Group: Default

%description man
man components for the s3fs-fuse package.


%prep
%setup -q -n s3fs-fuse-1.91
cd %{_builddir}/s3fs-fuse-1.91

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1646751418
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
%autogen --disable-static
make  %{?_smp_mflags}

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make %{?_smp_mflags} check || :

%install
export SOURCE_DATE_EPOCH=1646751418
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/s3fs-fuse
cp %{_builddir}/s3fs-fuse-1.91/COPYING %{buildroot}/usr/share/package-licenses/s3fs-fuse/06877624ea5c77efe3b7e39b0f909eda6e25a4ec
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/s3fs

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/s3fs-fuse/06877624ea5c77efe3b7e39b0f909eda6e25a4ec

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/s3fs.1
