#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: autogen
#
Name     : s3fs-fuse
Version  : 1.93
Release  : 12
URL      : https://github.com/s3fs-fuse/s3fs-fuse/archive/v1.93/s3fs-fuse-1.93.tar.gz
Source0  : https://github.com/s3fs-fuse/s3fs-fuse/archive/v1.93/s3fs-fuse-1.93.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-2.0
Requires: s3fs-fuse-bin = %{version}-%{release}
Requires: s3fs-fuse-license = %{version}-%{release}
Requires: s3fs-fuse-man = %{version}-%{release}
BuildRequires : attr-dev
BuildRequires : openssl-dev
BuildRequires : pkgconfig(fuse)
BuildRequires : pkgconfig(gnutls)
BuildRequires : pkgconfig(libcrypto)
BuildRequires : pkgconfig(libcurl)
BuildRequires : pkgconfig(libxml-2.0)
BuildRequires : pkgconfig(nettle)
BuildRequires : pkgconfig(nss)
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
# s3fs
s3fs allows Linux, macOS, and FreeBSD to mount an S3 bucket via [FUSE(Filesystem in Userspace)](https://github.com/libfuse/libfuse).
s3fs makes you operate files and directories in S3 bucket like a local file system.
s3fs preserves the native object format for files, allowing use of other tools like [AWS CLI](https://github.com/aws/aws-cli).

%package bin
Summary: bin components for the s3fs-fuse package.
Group: Binaries
Requires: s3fs-fuse-license = %{version}-%{release}

%description bin
bin components for the s3fs-fuse package.


%package license
Summary: license components for the s3fs-fuse package.
Group: Default

%description license
license components for the s3fs-fuse package.


%package man
Summary: man components for the s3fs-fuse package.
Group: Default

%description man
man components for the s3fs-fuse package.


%prep
%setup -q -n s3fs-fuse-1.93
cd %{_builddir}/s3fs-fuse-1.93
pushd ..
cp -a s3fs-fuse-1.93 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1692219311
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export FCFLAGS="$FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export FFLAGS="$FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export CXXFLAGS="$CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
%autogen --disable-static
make  %{?_smp_mflags}

pushd ../buildavx2/
export CFLAGS="$CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export CXXFLAGS="$CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FFLAGS="$FFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FCFLAGS="$FCFLAGS -m64 -march=x86-64-v3 "
export LDFLAGS="$LDFLAGS -m64 -march=x86-64-v3 "
%autogen --disable-static
make  %{?_smp_mflags}
popd
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make %{?_smp_mflags} check || :
cd ../buildavx2;
make %{?_smp_mflags} check || : || :

%install
export SOURCE_DATE_EPOCH=1692219311
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/s3fs-fuse
cp %{_builddir}/s3fs-fuse-%{version}/COPYING %{buildroot}/usr/share/package-licenses/s3fs-fuse/06877624ea5c77efe3b7e39b0f909eda6e25a4ec || :
pushd ../buildavx2/
%make_install_v3
popd
%make_install
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/V3/usr/bin/s3fs
/usr/bin/s3fs

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/s3fs-fuse/06877624ea5c77efe3b7e39b0f909eda6e25a4ec

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/s3fs.1
